## 基本说明

1. Go语言追求简洁、优雅，所以，Go语言不支持传统的try...catch...finally的这种处理
2. Go中引入的处理方式是： defer、panic、recover
3. Go中抛出一个 panic 的异常，然后在defer中，通过 recover 捕获这个异常，然后正常处理

```go
package main
import "fmt"

func test() {
	defer func() {
		err := recover()
		if err != nil {
			fmt.Printf("err类型 %T, err值 %v\n", err, err)
			// err类型 runtime.errorString, err值 runtime error: integer divide by zero
		}
	}()
	n1 := 10
	n2 := 0
	res := n1 / n2
	fmt.Println(res)
}

func main() {
	test()
	fmt.Println("main函数")
}
```

## 错误处理的好处

进行错误处理之后，程序不会轻易的挂掉，如果加入预警代码，就可以让程序更加的健壮。

## 自定义错误

### 介绍

Go程序中，也支持自定义错误，使用 `errors.New()` 和 `panic()` 内置函数。

1. `errors.New("错误说明")`，会返回一个error类型的值，表示一个错误
2. `panic()` 内置函数，接收一个 `interface{}` 类型的值（也就是任何值）作为参数。可以接收error类型的变量，**输出错误信息， 并退出程序**

```go
package  main
import (
	"fmt"
	"errors"
)

func test() (err error) {
	err = errors.New("自定义错误")
	return
}

func main() {
	err := test()
	panic(err)
	fmt.Println("main 函数")
}
```

![image-20211008095034474](https://gitee.com/wu_kang0718/image/raw/master//20211008095036402.png)















